export const COUNTRIES = [
  { code: "AF", name: "Afghanistan" },
  { code: "ZA", name: "Afrique du Sud" },
  { code: "AL", name: "Albanie" },
  { code: "DZ", name: "Algérie" },
  { code: "DE", name: "Allemagne" },
  { code: "AD", name: "Andorre" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua-et-Barbuda" },
  { code: "SA", name: "Arabie Saoudite" },
  { code: "AR", name: "Argentine" },
  { code: "AM", name: "Arménie" },
  { code: "AU", name: "Australie" },
  { code: "AT", name: "Autriche" },
  { code: "AZ", name: "Azerbaïdjan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahreïn" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbade" },
  { code: "BE", name: "Belgique" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Bénin" },
  { code: "BT", name: "Bhoutan" },
  { code: "BY", name: "Biélorussie" },
  { code: "MM", name: "Birmanie (Myanmar)" },
  { code: "BO", name: "Bolivie" },
  { code: "BA", name: "Bosnie-Herzégovine" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brésil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgarie" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodge" },
  { code: "CM", name: "Cameroun" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cap-Vert" },
  { code: "CL", name: "Chili" },
  { code: "CN", name: "Chine" },
  { code: "CY", name: "Chypre" },
  { code: "CO", name: "Colombie" },
  { code: "KM", name: "Comores" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (RDC)" },
  { code: "KP", name: "Corée du Nord" },
  { code: "KR", name: "Corée du Sud" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatie" },
  { code: "CU", name: "Cuba" },
  { code: "DK", name: "Danemark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominique" },
  { code: "EG", name: "Égypte" },
  { code: "AE", name: "Émirats Arabes Unis" },
  { code: "EC", name: "Équateur" },
  { code: "ER", name: "Érythrée" },
  { code: "ES", name: "Espagne" },
  { code: "EE", name: "Estonie" },
  { code: "US", name: "États-Unis" },
  { code: "ET", name: "Éthiopie" },
  { code: "FJ", name: "Fidji" },
  { code: "FI", name: "Finlande" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambie" },
  { code: "GE", name: "Géorgie" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Grèce" },
  { code: "GD", name: "Grenade" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinée" },
  { code: "GQ", name: "Guinée équatoriale" },
  { code: "GW", name: "Guinée-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haïti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hongrie" },
  { code: "IN", name: "Inde" },
  { code: "ID", name: "Indonésie" },
  { code: "IQ", name: "Irak" },
  { code: "IR", name: "Iran" },
  { code: "IE", name: "Irlande" },
  { code: "IS", name: "Islande" },
  { code: "IL", name: "Israël" },
  { code: "IT", name: "Italie" },
  { code: "JM", name: "Jamaïque" },
  { code: "JP", name: "Japon" },
  { code: "JO", name: "Jordanie" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KG", name: "Kirghizistan" },
  { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Koweït" },
  { code: "LA", name: "Laos" },
  { code: "LS", name: "Lesotho" },
  { code: "LV", name: "Lettonie" },
  { code: "LB", name: "Liban" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libye" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lituanie" },
  { code: "LU", name: "Luxembourg" },
  { code: "MK", name: "Macédoine du Nord" },
  { code: "MG", name: "Madagascar" },
  { code: "MY", name: "Malaisie" },
  { code: "MW", name: "Malawi" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malte" },
  { code: "MA", name: "Maroc" },
  { code: "MH", name: "Îles Marshall" },
  { code: "MU", name: "Maurice" },
  { code: "MR", name: "Mauritanie" },
  { code: "MX", name: "Mexique" },
  { code: "FM", name: "Micronésie" },
  { code: "MD", name: "Moldavie" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolie" },
  { code: "ME", name: "Monténégro" },
  { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibie" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Népal" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NU", name: "Niue" },
  { code: "NO", name: "Norvège" },
  { code: "NZ", name: "Nouvelle-Zélande" },
  { code: "OM", name: "Oman" },
  { code: "UG", name: "Ouganda" },
  { code: "UZ", name: "Ouzbékistan" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palaos" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée" },
  { code: "PY", name: "Paraguay" },
  { code: "NL", name: "Pays-Bas" },
  { code: "PE", name: "Pérou" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Pologne" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "CF", name: "République Centrafricaine" },
  { code: "DO", name: "République Dominicaine" },
  { code: "CZ", name: "République Tchèque" },
  { code: "RO", name: "Roumanie" },
  { code: "GB", name: "Royaume-Uni" },
  { code: "RU", name: "Russie" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint-Kitts-et-Nevis" },
  { code: "SM", name: "Saint-Marin" },
  { code: "VC", name: "Saint-Vincent-et-les-Grenadines" },
  { code: "LC", name: "Sainte-Lucie" },
  { code: "SV", name: "Salvador" },
  { code: "WS", name: "Samoa" },
  { code: "ST", name: "Sao Tomé-et-Principe" },
  { code: "SN", name: "Sénégal" },
  { code: "RS", name: "Serbie" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapour" },
  { code: "SK", name: "Slovaquie" },
  { code: "SI", name: "Slovénie" },
  { code: "SO", name: "Somalie" },
  { code: "SD", name: "Soudan" },
  { code: "SS", name: "Soudan du Sud" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SE", name: "Suède" },
  { code: "CH", name: "Suisse" },
  { code: "SR", name: "Suriname" },
  { code: "SZ", name: "Eswatini (Swaziland)" },
  { code: "SY", name: "Syrie" },
  { code: "TJ", name: "Tadjikistan" },
  { code: "TZ", name: "Tanzanie" },
  { code: "TD", name: "Tchad" },
  { code: "TH", name: "Thaïlande" },
  { code: "TL", name: "Timor oriental" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinité-et-Tobago" },
  { code: "TN", name: "Tunisie" },
  { code: "TM", name: "Turkménistan" },
  { code: "TR", name: "Turquie" },
  { code: "TV", name: "Tuvalu" },
  { code: "UA", name: "Ukraine" },
  { code: "UY", name: "Uruguay" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Viêt Nam" },
  { code: "YE", name: "Yémen" },
  { code: "ZM", name: "Zambie" },
  { code: "ZW", name: "Zimbabwe" }
].sort((a, b) => a.name.localeCompare(b.name));

export const CURRENCIES = [
  { code: "AFN", name: "Afghani Afghan" },
  { code: "ZAR", name: "Rand Sud-Africain" },
  { code: "ALL", name: "Lek Albanais" },
  { code: "DZD", name: "Dinar Algérien" },
  { code: "EUR", name: "Euro" },
  { code: "AOA", name: "Kwanza Angolais" },
  { code: "XCD", name: "Dollar des Caraïbes Orientales" },
  { code: "SAR", name: "Riyal Saoudien" },
  { code: "ARS", name: "Peso Argentin" },
  { code: "AMD", name: "Dram Arménien" },
  { code: "AUD", name: "Dollar Australien" },
  { code: "AZN", name: "Manat Azerbaïdjanais" },
  { code: "BSD", name: "Dollar des Bahamas" },
  { code: "BHD", name: "Dinar Bahreïni" },
  { code: "BDT", name: "Taka Bangladais" },
  { code: "BBD", name: "Dollar Barbadien" },
  { code: "BZD", name: "Dollar Bélizien" },
  { code: "XOF", name: "Franc CFA (BCEAO)" },
  { code: "BTN", name: "Ngultrum Bhoutanais" },
  { code: "BYN", name: "Rouble Biélorusse" },
  { code: "MMK", name: "Kyat Birman" },
  { code: "BOB", name: "Boliviano Bolivien" },
  { code: "BAM", name: "Mark Convertible de Bosnie" },
  { code: "BWP", name: "Pula Botswanais" },
  { code: "BRL", name: "Réal Brésilien" },
  { code: "BND", name: "Dollar Brunéien" },
  { code: "BGN", name: "Lev Bulgare" },
  { code: "BIF", name: "Franc Burundais" },
  { code: "KHR", name: "Riel Cambodgien" },
  { code: "XAF", name: "Franc CFA (BEAC)" },
  { code: "CAD", name: "Dollar Canadien" },
  { code: "CVE", name: "Escudo Cap-Verdien" },
  { code: "CLP", name: "Peso Chilien" },
  { code: "CNY", name: "Yuan Chinois" },
  { code: "COP", name: "Peso Colombien" },
  { code: "KMF", name: "Franc Comorien" },
  { code: "CDF", name: "Franc Congolais" },
  { code: "KPW", name: "Won Nord-Coréen" },
  { code: "KRW", name: "Won Sud-Coréen" },
  { code: "CRC", name: "Colón Costaricain" },
  { code: "HRK", name: "Kuna Croate" },
  { code: "CUP", name: "Peso Cubain" },
  { code: "DKK", name: "Couronne Danoise" },
  { code: "DJF", name: "Franc Djiboutien" },
  { code: "EGP", name: "Livre Égyptienne" },
  { code: "AED", name: "Dirham des Émirats Arabes Unis" },
  { code: "ERN", name: "Nakfa Érythréen" },
  { code: "USD", name: "Dollar Américain" },
  { code: "ETB", name: "Birr Éthiopien" },
  { code: "FJD", name: "Dollar Fidjien" },
  { code: "GMD", name: "Dalasi Gambien" },
  { code: "GEL", name: "Lari Géorgien" },
  { code: "GHS", name: "Cedi Ghanéen" },
  { code: "GTQ", name: "Quetzal Guatémaltèque" },
  { code: "GNF", name: "Franc Guinéen" },
  { code: "GYD", name: "Dollar Guyanien" },
  { code: "HTG", name: "Gourde Haïtienne" },
  { code: "HNL", name: "Lempira Hondurien" },
  { code: "HUF", name: "Forint Hongrois" },
  { code: "INR", name: "Roupie Indienne" },
  { code: "IDR", name: "Roupie Indonésienne" },
  { code: "IQD", name: "Dinar Irakien" },
  { code: "IRR", name: "Rial Iranien" },
  { code: "ILS", name: "Shekel Israélien" },
  { code: "JMD", name: "Dollar Jamaïcain" },
  { code: "JPY", name: "Yen Japonais" },
  { code: "JOD", name: "Dinar Jordanien" },
  { code: "KZT", name: "Tenge Kazakh" },
  { code: "KES", name: "Shilling Kenyan" },
  { code: "KGS", name: "Som Kirghize" },
  { code: "KWD", name: "Dinar Koweïtien" },
  { code: "LAK", name: "Kip Laotien" },
  { code: "LSL", name: "Loti Lesothan" },
  { code: "LBP", name: "Livre Libanaise" },
  { code: "LRD", name: "Dollar Libérien" },
  { code: "LYD", name: "Dinar Libyen" },
  { code: "CHF", name: "Franc Suisse" },
  { code: "MGA", name: "Ariary Malgache" },
  { code: "MYR", name: "Ringgit Malaisien" },
  { code: "MWK", name: "Kwacha Malawite" },
  { code: "MVR", name: "Rufiyaa Maldivienne" },
  { code: "MAD", name: "Dirham Marocain" },
  { code: "MUR", name: "Roupie Mauricienne" },
  { code: "MRU", name: "Ouguiya Mauritanienne" },
  { code: "MXN", name: "Peso Mexicain" },
  { code: "MDL", name: "Leu Moldave" },
  { code: "MNT", name: "Tugrik Mongol" },
  { code: "MZN", name: "Metical Mozambicain" },
  { code: "NAD", name: "Dollar Namibien" },
  { code: "NPR", name: "Roupie Népalaise" },
  { code: "NIO", name: "Córdoba Nicaraguayen" },
  { code: "NGN", name: "Naira Nigérian" },
  { code: "NOK", name: "Couronne Norvégienne" },
  { code: "NZD", name: "Dollar Néo-Zélandais" },
  { code: "OMR", name: "Rial Omanais" },
  { code: "UGX", name: "Shilling Ougandais" },
  { code: "UZS", name: "Sum Ouzbek" },
  { code: "PKR", name: "Roupie Pakistanaise" },
  { code: "PAB", name: "Balboa Panaméen" },
  { code: "PGK", name: "Kina Papou-Néo-Guinéen" },
  { code: "PYG", name: "Guaraní Paraguayen" },
  { code: "PEN", name: "Sol Péruvien" },
  { code: "PHP", name: "Peso Philippin" },
  { code: "PLN", name: "Zloty Polonais" },
  { code: "QAR", name: "Riyal Qatari" },
  { code: "DOP", name: "Peso Dominicain" },
  { code: "CZK", name: "Couronne Tchèque" },
  { code: "RON", name: "Leu Roumain" },
  { code: "GBP", name: "Livre Sterling" },
  { code: "RUB", name: "Rouble Russe" },
  { code: "RWF", name: "Franc Rwandais" },
  { code: "WST", name: "Tala Samoan" },
  { code: "STN", name: "Dobra Santoméen" },
  { code: "RSD", name: "Dinar Serbe" },
  { code: "SCR", name: "Roupie Seychelloise" },
  { code: "SLL", name: "Leone Sierra-Léonais" },
  { code: "SGD", name: "Dollar de Singapour" },
  { code: "SOS", name: "Shilling Somalien" },
  { code: "SDG", name: "Livre Soudanaise" },
  { code: "SSP", name: "Livre Sud-Soudanaise" },
  { code: "LKR", name: "Roupie Srilankaise" },
  { code: "SEK", name: "Couronne Suédoise" },
  { code: "SRD", name: "Dollar Surinamais" },
  { code: "SZL", name: "Lilangeni Swazi" },
  { code: "SYP", name: "Livre Syrienne" },
  { code: "TJS", name: "Somoni Tadjik" },
  { code: "TZS", name: "Shilling Tanzanien" },
  { code: "THB", name: "Baht Thaïlandais" },
  { code: "TOP", name: "Pa'anga Tongan" },
  { code: "TTD", name: "Dollar de Trinité-et-Tobago" },
  { code: "TND", name: "Dinar Tunisien" },
  { code: "TMT", name: "Manat Turkmène" },
  { code: "TRY", name: "Livre Turque" },
  { code: "UAH", name: "Hryvnia Ukrainienne" },
  { code: "UYU", name: "Peso Uruguayen" },
  { code: "VUV", name: "Vatu Vanuatuan" },
  { code: "VES", name: "Bolívar Vénézuélien" },
  { code: "VND", name: "Dong Vietnamien" },
  { code: "YER", name: "Rial Yéménite" },
  { code: "ZMW", name: "Kwacha Zambien" }
].sort((a, b) => a.name.localeCompare(b.name));
