export const COUNTRY_CODES = [
  { code: "MA", name: "Maroc", dialCode: "+212" },
  { code: "FR", name: "France", dialCode: "+33" },
  { code: "US", name: "United States", dialCode: "+1" },
  { code: "CA", name: "Canada", dialCode: "+1" },
  { code: "BE", name: "Belgique", dialCode: "+32" },
  { code: "CH", name: "Suisse", dialCode: "+41" },
  { code: "DZ", name: "Algérie", dialCode: "+213" },
  { code: "TN", name: "Tunisie", dialCode: "+216" },
  { code: "CI", name: "Côte d'Ivoire", dialCode: "+225" },
  { code: "SN", name: "Sénégal", dialCode: "+221" },
  { code: "CM", name: "Cameroun", dialCode: "+237" },
  { code: "ES", name: "Espagne", dialCode: "+34" },
  { code: "IT", name: "Italie", dialCode: "+39" },
  { code: "DE", name: "Allemagne", dialCode: "+49" },
  { code: "GB", name: "Royaume-Uni", dialCode: "+44" },
  { code: "AE", name: "Émirats Arabes Unis", dialCode: "+971" },
  { code: "SA", name: "Arabie Saoudite", dialCode: "+966" },
];
